import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialBaseline1783760966727 implements MigrationInterface {
    name = 'InitialBaseline1783760966727'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` uuid NOT NULL, \`resource\` varchar(50) NOT NULL, \`action\` varchar(50) NOT NULL, \`description\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` uuid NOT NULL, \`name\` varchar(100) NOT NULL, \`description\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` uuid NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`firstName\` varchar(100) NOT NULL, \`lastName\` varchar(100) NOT NULL, \`avatar\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`colorPalette\` varchar(20) NOT NULL DEFAULT 'indigo', \`darkMode\` tinyint NOT NULL DEFAULT 0, \`role_id\` uuid NOT NULL, \`refreshToken\` varchar(512) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`languages\` (\`id\` uuid NOT NULL, \`code\` varchar(10) NOT NULL, \`name\` varchar(100) NOT NULL, \`direction\` enum ('ltr', 'rtl') NOT NULL DEFAULT 'ltr', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_7397752718d1c9eb873722ec9b\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`template_field_labels\` (\`id\` uuid NOT NULL, \`template_field_id\` uuid NOT NULL, \`language_id\` uuid NOT NULL, \`label\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`template_fields\` (\`id\` uuid NOT NULL, \`template_id\` uuid NOT NULL, \`fieldKey\` varchar(100) NOT NULL, \`fieldType\` enum ('text', 'textarea', 'number', 'date', 'image') NOT NULL DEFAULT 'text', \`sortOrder\` int NOT NULL DEFAULT '0', \`required\` tinyint NOT NULL DEFAULT 0, \`groupKey\` varchar(100) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`templates\` (\`id\` uuid NOT NULL, \`type\` enum ('designer', 'word', 'simple') NOT NULL DEFAULT 'designer', \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`pricePerPage\` decimal(10,2) NOT NULL DEFAULT '0.00', \`discountedPricePerPage\` decimal(10,2) NULL, \`layoutJson\` json NULL, \`wordFilePath\` varchar(500) NULL, \`wordFileName\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`label_options\` (\`id\` uuid NOT NULL, \`category\` varchar(50) NOT NULL, \`value\` varchar(100) NOT NULL, \`sortOrder\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`freeform_job_types\` (\`id\` uuid NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`pricePerPage\` decimal(10,2) NOT NULL DEFAULT '0.00', \`discountedPricePerPage\` decimal(10,2) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`app_settings\` (\`id\` uuid NOT NULL, \`companyName\` varchar(255) NOT NULL DEFAULT '', \`companyAddress\` text NULL, \`companyLogo\` varchar(255) NULL, \`baseCurrency\` varchar(10) NOT NULL DEFAULT 'USD', \`invoicePrefix\` varchar(50) NULL, \`maxUploadSizeMb\` int NOT NULL DEFAULT '5', \`allowedFileTypes\` json NULL, \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` uuid NOT NULL, \`user_id\` uuid NOT NULL, \`type\` enum ('job_status_change', 'deadline_approaching', 'invoice_overdue', 'job_assigned') NOT NULL, \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`link\` varchar(500) NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contacts\` (\`id\` uuid NOT NULL, \`client_id\` uuid NOT NULL, \`firstName\` varchar(100) NOT NULL, \`lastName\` varchar(100) NOT NULL, \`email\` varchar(255) NULL, \`phone\` varchar(50) NULL, \`role\` varchar(100) NULL, \`notes\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`passport_copies\` (\`id\` uuid NOT NULL, \`client_id\` uuid NOT NULL, \`label\` varchar(255) NOT NULL, \`filePath\` varchar(500) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`mimeType\` varchar(100) NOT NULL, \`fileSize\` int NOT NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`client_emails\` (\`id\` uuid NOT NULL, \`client_id\` uuid NOT NULL, \`email\` varchar(255) NOT NULL, \`label\` varchar(100) NULL, \`isPrimary\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`client_phones\` (\`id\` uuid NOT NULL, \`client_id\` uuid NOT NULL, \`phone\` varchar(50) NOT NULL, \`label\` varchar(100) NULL, \`isPrimary\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`client_addresses\` (\`id\` uuid NOT NULL, \`client_id\` uuid NOT NULL, \`address\` text NOT NULL, \`label\` varchar(100) NULL, \`isPrimary\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clients\` (\`id\` uuid NOT NULL, \`type\` enum ('company', 'person') NOT NULL, \`name\` varchar(255) NOT NULL, \`taxId\` varchar(100) NULL, \`notes\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_users\` (\`id\` uuid NOT NULL, \`job_id\` uuid NOT NULL, \`user_id\` uuid NOT NULL, \`permissionLevel\` enum ('view', 'edit') NOT NULL DEFAULT 'edit', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_files\` (\`id\` uuid NOT NULL, \`job_id\` uuid NOT NULL, \`category\` enum ('source', 'translated') NOT NULL, \`fileName\` varchar(255) NOT NULL, \`filePath\` varchar(500) NOT NULL, \`fileSize\` int NOT NULL, \`mimeType\` varchar(100) NOT NULL, \`linked_from_job_id\` varchar(255) NULL, \`uploaded_by_user_id\` varchar(255) NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_line_items\` (\`id\` uuid NOT NULL, \`job_id\` uuid NOT NULL, \`description\` varchar(255) NOT NULL, \`templateId\` varchar(255) NULL, \`pageCount\` int NOT NULL DEFAULT '1', \`pricePerPage\` decimal(10,2) NOT NULL DEFAULT '0.00', \`useDiscountedPrice\` tinyint NOT NULL DEFAULT 0, \`discountedPricePerPage\` decimal(10,2) NULL, \`lineTotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`sortOrder\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`jobs\` (\`id\` uuid NOT NULL, \`jobNumber\` varchar(20) NOT NULL, \`type\` enum ('template', 'freeform') NOT NULL DEFAULT 'template', \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`client_id\` uuid NOT NULL, \`contact_id\` uuid NULL, \`source_language_id\` uuid NOT NULL, \`target_language_id\` uuid NULL, \`status\` enum ('quote', 'accepted', 'in_progress', 'delivered', 'invoiced', 'paid', 'lost', 'cancelled') NOT NULL DEFAULT 'in_progress', \`deadline\` date NULL, \`calculatedTotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`finalPrice\` decimal(10,2) NULL, \`isFreeOfCharge\` tinyint NOT NULL DEFAULT 0, \`freeOfChargeReason\` text NULL, \`paymentCurrency\` varchar(10) NULL, \`paymentAmount\` decimal(10,2) NULL, \`notes\` text NULL, \`created_by_user_id\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_78d4c0fef5e31a5e8488e4f9c5\` (\`jobNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoice_items\` (\`id\` uuid NOT NULL, \`invoice_id\` uuid NOT NULL, \`job_id\` uuid NULL, \`description\` varchar(500) NOT NULL, \`quantity\` decimal(10,2) NOT NULL DEFAULT '1.00', \`unitPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`lineTotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`sortOrder\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoices\` (\`id\` uuid NOT NULL, \`invoiceNumber\` varchar(20) NOT NULL, \`client_id\` uuid NOT NULL, \`status\` enum ('draft', 'sent', 'paid', 'overdue', 'cancelled') NOT NULL DEFAULT 'draft', \`issueDate\` date NOT NULL, \`dueDate\` date NOT NULL, \`subtotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`taxRate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`taxAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total\` decimal(10,2) NOT NULL DEFAULT '0.00', \`notes\` text NULL, \`currency\` varchar(10) NOT NULL DEFAULT 'USD', \`paidAt\` datetime NULL, \`paidAmount\` decimal(10,2) NULL, \`created_by_user_id\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_bf8e0f9dd4558ef209ec111782\` (\`invoiceNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_field_values\` (\`id\` uuid NOT NULL, \`document_id\` uuid NOT NULL, \`template_field_id\` uuid NOT NULL, \`pageNumber\` int NOT NULL DEFAULT '1', \`entryIndex\` int NULL, \`value\` text NOT NULL DEFAULT '', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`documents\` (\`id\` uuid NOT NULL, \`job_id\` uuid NOT NULL, \`template_id\` uuid NOT NULL, \`status\` enum ('draft', 'completed') NOT NULL DEFAULT 'draft', \`cloned_from_id\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sessions\` (\`id\` uuid NOT NULL, \`userId\` varchar(255) NOT NULL, \`refreshTokenHash\` varchar(512) NOT NULL, \`ipAddress\` varchar(45) NOT NULL, \`userAgentHash\` varchar(64) NOT NULL, \`userAgentRaw\` varchar(512) NULL, \`revoked\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`lastUsedAt\` datetime NOT NULL, \`expiresAt\` datetime NOT NULL, \`user_id\` uuid NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_tokens\` (\`id\` uuid NOT NULL, \`token\` varchar(64) NOT NULL, \`userId\` varchar(255) NOT NULL, \`expiresAt\` datetime NOT NULL, \`used\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_ab673f0e63eac966762155508e\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invite_tokens\` (\`id\` uuid NOT NULL, \`token\` varchar(64) NOT NULL, \`email\` varchar(255) NOT NULL, \`roleId\` varchar(255) NULL, \`expiresAt\` datetime NOT NULL, \`used\` tinyint NOT NULL DEFAULT 0, \`usedByUserId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_1b428e1defa2fd21e8f770e93f\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`role_id\` uuid NOT NULL, \`permission_id\` uuid NOT NULL, INDEX \`IDX_178199805b901ccd220ab7740e\` (\`role_id\`), INDEX \`IDX_17022daf3f885f7d35423e9971\` (\`permission_id\`), PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`template_field_labels\` ADD CONSTRAINT \`FK_1f6e73b721897fdd6099f71d09c\` FOREIGN KEY (\`template_field_id\`) REFERENCES \`template_fields\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`template_field_labels\` ADD CONSTRAINT \`FK_3849b9f40771885dfa4ebfb9ff9\` FOREIGN KEY (\`language_id\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`template_fields\` ADD CONSTRAINT \`FK_609a78fd29a08b0c4f00ab6c815\` FOREIGN KEY (\`template_id\`) REFERENCES \`templates\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD CONSTRAINT \`FK_72d1013c43a0198e905290831e5\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`passport_copies\` ADD CONSTRAINT \`FK_abb11eed621d5e3befcf7c2716a\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`client_emails\` ADD CONSTRAINT \`FK_5566c1f47ddd7a2cea64c039bd8\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`client_phones\` ADD CONSTRAINT \`FK_6e22d73120616b907ee488f1373\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`client_addresses\` ADD CONSTRAINT \`FK_a88557f9d4f0eebd10e1c46af73\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`job_users\` ADD CONSTRAINT \`FK_8920bde6d2bd68e2ccd7b1ea3f7\` FOREIGN KEY (\`job_id\`) REFERENCES \`jobs\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`job_users\` ADD CONSTRAINT \`FK_5ad32dccf7718a9c725ff82576c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`job_files\` ADD CONSTRAINT \`FK_7d15ccfea066b5396ab111f6f95\` FOREIGN KEY (\`job_id\`) REFERENCES \`jobs\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`job_line_items\` ADD CONSTRAINT \`FK_22688bf34b0fc61dd06cbba0ca5\` FOREIGN KEY (\`job_id\`) REFERENCES \`jobs\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD CONSTRAINT \`FK_dec6205e2cd13841763710f9892\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD CONSTRAINT \`FK_2142c311b22cec2e0d0e4dbb829\` FOREIGN KEY (\`contact_id\`) REFERENCES \`contacts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD CONSTRAINT \`FK_e9f64be7eb2da8b74c139a6b9da\` FOREIGN KEY (\`source_language_id\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD CONSTRAINT \`FK_7aaede5a89951416fa2c74c2b22\` FOREIGN KEY (\`target_language_id\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_dc991d555664682cfe892eea2c1\` FOREIGN KEY (\`invoice_id\`) REFERENCES \`invoices\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_686ff1d1881270fba5d29009d1c\` FOREIGN KEY (\`job_id\`) REFERENCES \`jobs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_5534ba11e10f1a9953cbdaabf16\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_field_values\` ADD CONSTRAINT \`FK_ae58fe5db4112f667c8e780eee2\` FOREIGN KEY (\`document_id\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_field_values\` ADD CONSTRAINT \`FK_1c9977259ad56376e32c727cdec\` FOREIGN KEY (\`template_field_id\`) REFERENCES \`template_fields\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_28d96e483a1e1a921a4d60029ba\` FOREIGN KEY (\`job_id\`) REFERENCES \`jobs\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_3c3bacd617c899c37223ebbb037\` FOREIGN KEY (\`template_id\`) REFERENCES \`templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD CONSTRAINT \`FK_085d540d9f418cfbdc7bd55bb19\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_178199805b901ccd220ab7740ec\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_17022daf3f885f7d35423e9971e\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permissions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_17022daf3f885f7d35423e9971e\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_178199805b901ccd220ab7740ec\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP FOREIGN KEY \`FK_085d540d9f418cfbdc7bd55bb19\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_3c3bacd617c899c37223ebbb037\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_28d96e483a1e1a921a4d60029ba\``);
        await queryRunner.query(`ALTER TABLE \`document_field_values\` DROP FOREIGN KEY \`FK_1c9977259ad56376e32c727cdec\``);
        await queryRunner.query(`ALTER TABLE \`document_field_values\` DROP FOREIGN KEY \`FK_ae58fe5db4112f667c8e780eee2\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_5534ba11e10f1a9953cbdaabf16\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_686ff1d1881270fba5d29009d1c\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_dc991d555664682cfe892eea2c1\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP FOREIGN KEY \`FK_7aaede5a89951416fa2c74c2b22\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP FOREIGN KEY \`FK_e9f64be7eb2da8b74c139a6b9da\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP FOREIGN KEY \`FK_2142c311b22cec2e0d0e4dbb829\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP FOREIGN KEY \`FK_dec6205e2cd13841763710f9892\``);
        await queryRunner.query(`ALTER TABLE \`job_line_items\` DROP FOREIGN KEY \`FK_22688bf34b0fc61dd06cbba0ca5\``);
        await queryRunner.query(`ALTER TABLE \`job_files\` DROP FOREIGN KEY \`FK_7d15ccfea066b5396ab111f6f95\``);
        await queryRunner.query(`ALTER TABLE \`job_users\` DROP FOREIGN KEY \`FK_5ad32dccf7718a9c725ff82576c\``);
        await queryRunner.query(`ALTER TABLE \`job_users\` DROP FOREIGN KEY \`FK_8920bde6d2bd68e2ccd7b1ea3f7\``);
        await queryRunner.query(`ALTER TABLE \`client_addresses\` DROP FOREIGN KEY \`FK_a88557f9d4f0eebd10e1c46af73\``);
        await queryRunner.query(`ALTER TABLE \`client_phones\` DROP FOREIGN KEY \`FK_6e22d73120616b907ee488f1373\``);
        await queryRunner.query(`ALTER TABLE \`client_emails\` DROP FOREIGN KEY \`FK_5566c1f47ddd7a2cea64c039bd8\``);
        await queryRunner.query(`ALTER TABLE \`passport_copies\` DROP FOREIGN KEY \`FK_abb11eed621d5e3befcf7c2716a\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP FOREIGN KEY \`FK_72d1013c43a0198e905290831e5\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`template_fields\` DROP FOREIGN KEY \`FK_609a78fd29a08b0c4f00ab6c815\``);
        await queryRunner.query(`ALTER TABLE \`template_field_labels\` DROP FOREIGN KEY \`FK_3849b9f40771885dfa4ebfb9ff9\``);
        await queryRunner.query(`ALTER TABLE \`template_field_labels\` DROP FOREIGN KEY \`FK_1f6e73b721897fdd6099f71d09c\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`DROP INDEX \`IDX_17022daf3f885f7d35423e9971\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_178199805b901ccd220ab7740e\` ON \`role_permissions\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_1b428e1defa2fd21e8f770e93f\` ON \`invite_tokens\``);
        await queryRunner.query(`DROP TABLE \`invite_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_ab673f0e63eac966762155508e\` ON \`password_reset_tokens\``);
        await queryRunner.query(`DROP TABLE \`password_reset_tokens\``);
        await queryRunner.query(`DROP TABLE \`sessions\``);
        await queryRunner.query(`DROP TABLE \`documents\``);
        await queryRunner.query(`DROP TABLE \`document_field_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_bf8e0f9dd4558ef209ec111782\` ON \`invoices\``);
        await queryRunner.query(`DROP TABLE \`invoices\``);
        await queryRunner.query(`DROP TABLE \`invoice_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_78d4c0fef5e31a5e8488e4f9c5\` ON \`jobs\``);
        await queryRunner.query(`DROP TABLE \`jobs\``);
        await queryRunner.query(`DROP TABLE \`job_line_items\``);
        await queryRunner.query(`DROP TABLE \`job_files\``);
        await queryRunner.query(`DROP TABLE \`job_users\``);
        await queryRunner.query(`DROP TABLE \`clients\``);
        await queryRunner.query(`DROP TABLE \`client_addresses\``);
        await queryRunner.query(`DROP TABLE \`client_phones\``);
        await queryRunner.query(`DROP TABLE \`client_emails\``);
        await queryRunner.query(`DROP TABLE \`passport_copies\``);
        await queryRunner.query(`DROP TABLE \`contacts\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`app_settings\``);
        await queryRunner.query(`DROP TABLE \`freeform_job_types\``);
        await queryRunner.query(`DROP TABLE \`label_options\``);
        await queryRunner.query(`DROP TABLE \`templates\``);
        await queryRunner.query(`DROP TABLE \`template_fields\``);
        await queryRunner.query(`DROP TABLE \`template_field_labels\``);
        await queryRunner.query(`DROP INDEX \`IDX_7397752718d1c9eb873722ec9b\` ON \`languages\``);
        await queryRunner.query(`DROP TABLE \`languages\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`permissions\``);
    }

}
